services:
  - type: web
    name: orderflow-integrator
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ORDERFLOW_ENVIRONMENT
        value: production
      - key: ORDERFLOW_DATABASE_URL
        fromDatabase:
          name: orderflow-db
          property: connectionString
      - key: ORDERFLOW_REDIS_URL
        fromService:
          type: keyvalue
          name: orderflow-redis
          property: connectionString
      - key: ORDERFLOW_API_KEY
        generateValue: true
  - type: worker
    name: orderflow-worker
    runtime: docker
    plan: starter
    dockerCommand: celery -A app.celery_app.celery_app worker --loglevel=INFO --concurrency=2
    envVars:
      - key: ORDERFLOW_ENVIRONMENT
        value: production
      - key: ORDERFLOW_DATABASE_URL
        fromDatabase:
          name: orderflow-db
          property: connectionString
      - key: ORDERFLOW_REDIS_URL
        fromService:
          type: keyvalue
          name: orderflow-redis
          property: connectionString
  - type: keyvalue
    name: orderflow-redis
    plan: free
    ipAllowList: []

databases:
  - name: orderflow-db
    plan: free
    databaseName: orderflow
    user: orderflow
